package com.hackaton.ulibre.tablero;

/** Enum de PostgreSQL {@code tipo_hito}. */
public enum TipoHito {
    LLEGADA_PACIENTE, INGRESO_QUIROFANO, TABLERO_INICIADO, PREANESTESIA_COMPLETADA, ANESTESIA_INICIADA,
    PREINCISION_COMPLETADA, CIRUGIA_INICIADA, CIRUGIA_FINALIZADA, SALIDA_COMPLETADA, TRASLADO_A_RECUPERACION
}
